export type LawCategory = 'act' | 'rule' | 'procedure' | 'directive' | 'guideline' | 'circular';
export type GovLevel = 'federal' | 'provincial';

export interface LawDocument {
  id: string;
  title_ne: string;
  title_en: string;
  category: LawCategory;
  category_name_ne: string; // ऐन, नियमावली, कार्यविधि, निर्देशिका, मार्गदर्शन, परिपत्र
  gov_level: GovLevel;
  province_name_ne?: string; // कोशी, बागमती आदि
  province_id?: string;
  issuing_authority: string;
  publication_date_bs: string;
  effective_date_bs: string;
  is_amended: boolean;
  amendment_date_bs?: string;
  description_ne: string;
  keywords: string[];
  pdf_url: string;
  file_size: string;
  source: string;
}

export const LAW_CATEGORIES: { id: LawCategory; name_ne: string; desc: string }[] = [
  { id: 'act', name_ne: 'ऐन (Acts)', desc: 'संसद् वा प्रदेश सभाबाट पारित मूल कानुनी ऐनहरू' },
  { id: 'rule', name_ne: 'नियमावली (Regulations)', desc: 'ऐन कार्यान्वयनका लागि मन्त्रिपरिषद्बाट स्वीकृत नियमावलीहरू' },
  { id: 'procedure', name_ne: 'कार्यविधि (Procedures)', desc: 'सेवा प्रवाह तथा कार्यक्रम सञ्चालनका कार्यविधिहरू' },
  { id: 'directive', name_ne: 'निर्देशिका (Directives)', desc: 'कार्यक्रम कार्यान्वयन र अनुगमनका निर्देशिकाहरू' },
  { id: 'guideline', name_ne: 'मार्गदर्शन (Guidelines)', desc: 'प्राविधिक तथा नीतिगत मार्गदर्शनहरू' },
  { id: 'circular', name_ne: 'परिपत्रहरू (Circulars)', desc: 'मन्त्रालय तथा स्थानीय तहका आधिकारिक परिपत्रहरू' },
];

export const NEPAL_PROVINCES = [
  { id: 'koshi', name_ne: 'कोशी प्रदेश', name_en: 'Koshi Province' },
  { id: 'madhesh', name_ne: 'मधेश प्रदेश', name_en: 'Madhesh Province' },
  { id: 'bagmati', name_ne: 'बागमती प्रदेश', name_en: 'Bagmati Province' },
  { id: 'gandaki', name_ne: 'गण्डकी प्रदेश', name_en: 'Gandaki Province' },
  { id: 'lumbini', name_ne: 'लुम्बिनी प्रदेश', name_en: 'Lumbini Province' },
  { id: 'karnali', name_ne: 'कर्णाली प्रदेश', name_en: 'Karnali Province' },
  { id: 'sudurpashchim', name_ne: 'सुदूरपश्चिम प्रदेश', name_en: 'Sudurpashchim Province' },
];

export const LEGAL_DOCUMENTS: LawDocument[] = [
  // FEDERAL LAWS
  {
    id: "law-fed-01",
    title_ne: "अपाङ्गता भएका व्यक्तिको अधिकार सम्बन्धी ऐन, २०७४",
    title_en: "Rights of Persons with Disabilities Act, 2017 (2074 BS)",
    category: "act",
    category_name_ne: "ऐन",
    gov_level: "federal",
    issuing_authority: "नेपाल सरकार, संघीय संसद्",
    publication_date_bs: "२०७४/०६/२९",
    effective_date_bs: "२०७४/०६/२९",
    is_amended: true,
    amendment_date_bs: "२०७५/११/१९",
    description_ne: "नेपालको संविधान बमोजिम अपाङ्गता भएका व्यक्तिको मानव अधिकार तथा मौलिक हकको संरक्षण, सम्मान, प्रवर्धन र समानताका आधारमा समाजमा मर्यादित जीवनयापन गर्न पाउने अधिकार सुनिश्चित गर्न बनेको मूल ऐन। यस ऐनले अपाङ्गतालाई १० प्रकारमा वर्गीकरण गरी ४ प्रकारका परिचयपत्रको व्यवस्था गरेको छ।",
    keywords: ["अपाङ्गता अधिकार ऐन", "१० प्रकार", "परिचयपत्र", "मानव अधिकार", "समानता", "२०७४"],
    pdf_url: "#",
    file_size: "१.८ MB",
    source: "नेपाल कानुन आयोग / राजपत्र",
  },
  {
    id: "law-fed-02",
    title_ne: "अपाङ्गता भएका व्यक्तिको अधिकार सम्बन्धी नियमावली, २०७७",
    title_en: "Rights of Persons with Disabilities Rules, 2020 (2077 BS)",
    category: "rule",
    category_name_ne: "नियमावली",
    gov_level: "federal",
    issuing_authority: "नेपाल सरकार, महिला, बालबालिका तथा ज्येष्ठ नागरिक मन्त्रालय",
    publication_date_bs: "२०७७/०५/२९",
    effective_date_bs: "२०७७/०५/२९",
    is_amended: false,
    description_ne: "अपाङ्गता भएका व्यक्तिको अधिकार सम्बन्धी ऐन, २०७४ को कार्यान्वयनका लागि स्थानीय तहमा अपाङ्गता समन्वय समिति गठन, परिचयपत्र सिफारिस तथा वितरण प्रक्रिया, निशुल्क शिक्षा, स्वास्थ्य र आरक्षण कार्यान्वयन सम्बन्धी विस्तृत नियमावली।",
    keywords: ["नियमावली", "समन्वय समिति", "परिचयपत्र वितरण प्रक्रिया", "२०७७"],
    pdf_url: "#",
    file_size: "२.४ MB",
    source: "महिला, बालबालिका तथा ज्येष्ठ नागरिक मन्त्रालय",
  },
  {
    id: "law-fed-03",
    title_ne: "अपाङ्गता परिचयपत्र वितरण कार्यविधि, २०७५",
    title_en: "Disability Identity Card Distribution Procedure, 2075 BS",
    category: "procedure",
    category_name_ne: "कार्यविधि",
    gov_level: "federal",
    issuing_authority: "महिला, बालबालिका तथा ज्येष्ठ नागरिक मन्त्रालय",
    publication_date_bs: "२०७५/०३/१५",
    effective_date_bs: "२०७५/०३/१५",
    is_amended: true,
    amendment_date_bs: "२०७८/०१/१०",
    description_ne: "स्थानीय तहबाट वितरण गरिने रातो, निलो, पहेलो र सेतो परिचयपत्र वितरणका मापदण्ड, चिकित्सक तथा स्वास्थ्य परीक्षण प्रमाणीकरण, र समन्वय समितिको कार्यविधि।",
    keywords: ["परिचयपत्र कार्यविधि", "रातो निलो पहेलो सेतो", "मापदण्ड", "२०७५"],
    pdf_url: "#",
    file_size: "१.२ MB",
    source: "मन्त्रालय कार्यविधि सङ्ग्रह",
  },
  {
    id: "law-fed-04",
    title_ne: "अपाङ्गता सहायता सहजकर्ता परिचालन तथा कार्य सञ्चालन निर्देशिका, २०८०",
    title_en: "Disability Facilitator Mobilization and Operation Directives, 2080 BS",
    category: "directive",
    category_name_ne: "निर्देशिका",
    gov_level: "federal",
    issuing_authority: "महिला, बालबालिका तथा ज्येष्ठ नागरिक मन्त्रालय / स्थानीय तह",
    publication_date_bs: "२०८०/०४/०१",
    effective_date_bs: "२०८०/०४/०१",
    is_amended: false,
    description_ne: "स्थानीय तहका अपाङ्गता सहायता कक्षहरूमा कार्यरत सहजकर्ताहरूको काम, कर्तव्य, अधिकार, गृहभेट, तथ्यांक संकलन, सहायक सामग्री सिफारिस र वार्षिक प्रतिवेदन पेश गर्ने निर्देशिका।",
    keywords: ["सहजकर्ता निर्देशिका", "गृहभेट", "वार्षिक प्रतिवेदन", "सहायता कक्ष", "२०८०"],
    pdf_url: "#",
    file_size: "१.५ MB",
    source: "सामाजिक विकास मन्त्रालय",
  },
  {
    id: "law-fed-05",
    title_ne: "पहुँचयुक्त भौतिक संरचना तथा सञ्चार सेवा सम्बन्धी निर्देशिका, २०६९ (परिमार्जित)",
    title_en: "Accessible Physical Infrastructure and Communication Services Directives, 2069 (Revised)",
    category: "directive",
    category_name_ne: "निर्देशिका",
    gov_level: "federal",
    issuing_authority: "नेपाल सरकार, भौतिक पूर्वाधार तथा यातायात मन्त्रालय",
    publication_date_bs: "२०६९/११/०६",
    effective_date_bs: "२०६९/११/०६",
    is_amended: true,
    amendment_date_bs: "२०७६/०९/१२",
    description_ne: "सार्वजनिक भवन, सडक, यातायातका साधन, विद्यालय, अस्पताल तथा शौचालयहरू अपाङ्गतामैत्री (र्‍याम्प, टेक्टायल, ब्रेल, साङ्केतिक भाषा) निर्माण गर्ने राष्ट्रिय प्राविधिक मापदण्ड।",
    keywords: ["पहुँचयुक्त संरचना", "र्‍याम्प", "अपाङ्गतामैत्री शौचालय", "टेक्टायल", "२०६९"],
    pdf_url: "#",
    file_size: "३.१ MB",
    source: "सहरी विकास मन्त्रालय",
  },
  {
    id: "law-fed-06",
    title_ne: "अपाङ्गता भएका व्यक्तिका लागि सहायक सामग्री व्यवस्थापन तथा वितरण मार्गदर्शन, २०७९",
    title_en: "Guidelines for Management and Distribution of Assistive Devices, 2079 BS",
    category: "guideline",
    category_name_ne: "मार्गदर्शन",
    gov_level: "federal",
    issuing_authority: "महिला, बालबालिका तथा ज्येष्ठ नागरिक मन्त्रालय",
    publication_date_bs: "२०७९/०२/२०",
    effective_date_bs: "२०७९/०२/२०",
    is_amended: false,
    description_ne: "अपाङ्गता भएका व्यक्तिको आवश्यकता पहिचान, नापजाँच (Measurement), गुणस्तर प्रमाणीकरण, ह्वीलचेयर, सेतो छडी, श्रवण यन्त्र लगायतका सामग्री वितरण तथा मर्मतसम्भार मार्गदर्शन।",
    keywords: ["सहायक सामग्री मार्गदर्शन", "ह्वीलचेयर", "नापजाँच", "वितरण", "२०७९"],
    pdf_url: "#",
    file_size: "१.६ MB",
    source: "राष्ट्रिय अपाङ्ग महासंघ / मन्त्रालय",
  },
  {
    id: "law-fed-07",
    title_ne: "सार्वजनिक यातायातमा अपाङ्गता भएका व्यक्तिका लागि ५० प्रतिशत छुट सम्बन्धी परिपत्र",
    title_en: "Circular on 50% Transport Fare Concession for Persons with Disabilities",
    category: "circular",
    category_name_ne: "परिपत्र",
    gov_level: "federal",
    issuing_authority: "यातायात व्यवस्था विभाग, नेपाल सरकार",
    publication_date_bs: "२०७६/०८/१५",
    effective_date_bs: "२०७६/०८/१५",
    is_amended: false,
    description_ne: "सबै प्रकारका सार्वजनिक यातायातका साधनहरूमा अपाङ्गता परिचयपत्र बाहकलाई भाडामा ५० प्रतिशत छुट दिने र २ वटा सिट सुरक्षित राख्ने सम्बन्धी राष्ट्रव्यापी परिपत्र।",
    keywords: ["यातायात छुट", "५० प्रतिशत", "परिपत्र", "यातायात व्यवस्था"],
    pdf_url: "#",
    file_size: "५४० KB",
    source: "यातायात व्यवस्था विभाग",
  },

  // PROVINCIAL LAWS - KOSHI PROVINCE
  {
    id: "law-prov-koshi-01",
    title_ne: "कोशी प्रदेश अपाङ्गता भएका व्यक्तिको अधिकार तथा संरक्षण ऐन, २०८०",
    title_en: "Koshi Province Rights and Protection of Persons with Disabilities Act, 2080 BS",
    category: "act",
    category_name_ne: "ऐन",
    gov_level: "provincial",
    province_id: "koshi",
    province_name_ne: "कोशी प्रदेश",
    issuing_authority: "कोशी प्रदेश सभा, विराटनगर",
    publication_date_bs: "२०८०/०५/१२",
    effective_date_bs: "२०८०/०५/१२",
    is_amended: false,
    description_ne: "कोशी प्रदेश भित्रका १४ वटै जिल्लामा अपाङ्गता भएका नागरिकहरूको मौलिक हकको कार्यान्वयन, शिक्षा, स्वास्थ्य, पुनर्स्थापना केन्द्र, सामाजिक सुरक्षा र सहायता कक्ष सञ्चालनका लागि बनेको प्रदेश स्तरीय ऐन।",
    keywords: ["कोशी प्रदेश ऐन", "विराटनगर", "संरक्षण", "पुनर्स्थापना", "२०८०"],
    pdf_url: "#",
    file_size: "२.१ MB",
    source: "कोशी प्रदेश राजपत्र",
  },
  {
    id: "law-prov-koshi-02",
    title_ne: "कोशी प्रदेश स्थानीय तह अपाङ्गता सहायता कक्ष सञ्चालन कार्यविधि, २०८१",
    title_en: "Koshi Province Local Level Disability Support Desk Operation Procedure, 2081 BS",
    category: "procedure",
    category_name_ne: "कार्यविधि",
    gov_level: "provincial",
    province_id: "koshi",
    province_name_ne: "कोशी प्रदेश",
    issuing_authority: "सामाजिक विकास मन्त्रालय, कोशी प्रदेश",
    publication_date_bs: "२०८१/०२/०४",
    effective_date_bs: "२०८१/०२/०४",
    is_amended: false,
    description_ne: "कोशी प्रदेशका १३७ वटै स्थानीय तहमा अपाङ्गता सहायता कक्ष स्थापना, सहजकर्ता व्यवस्थापन, बजेट विनियोजन र डिजिटल वार्षिक प्रतिवेदन (DIC) प्रविष्टि सम्बन्धी आधिकारिक कार्यविधि।",
    keywords: ["सहायता कक्ष कार्यविधि", "१३७ स्थानीय तह", "कोशी प्रदेश", "सहजकर्ता", "२०८१"],
    pdf_url: "#",
    file_size: "१.४ MB",
    source: "सामाजिक विकास मन्त्रालय, कोशी प्रदेश",
  },
  {
    id: "law-prov-koshi-03",
    title_ne: "कोशी प्रदेश सामुदायिक पुनर्स्थापना (CBR) तथा समावेशी शिक्षा निर्देशिका, २०७९",
    title_en: "Koshi Province Community Based Rehabilitation (CBR) & Inclusive Education Directives, 2079 BS",
    category: "directive",
    category_name_ne: "निर्देशिका",
    gov_level: "provincial",
    province_id: "koshi",
    province_name_ne: "कोशी प्रदेश",
    issuing_authority: "सामाजिक विकास मन्त्रालय, कोशी प्रदेश",
    publication_date_bs: "२०७९/०९/२५",
    effective_date_bs: "२०७९/०९/२५",
    is_amended: false,
    description_ne: "समुदायमा आधारित पुनर्स्थापना कार्यक्रम, बालबालिकाका लागि स्रोत कक्षा सञ्चालन, घरमा आधारित शिक्षा र आवासीय छात्रवृत्ति प्रबन्ध सम्बन्धी प्रदेश स्तरीय निर्देशिका।",
    keywords: ["CBR निर्देशिका", "समावेशी शिक्षा", "स्रोत कक्षा", "कोशी", "२०७९"],
    pdf_url: "#",
    file_size: "१.९ MB",
    source: "सामाजिक विकास मन्त्रालय, कोशी प्रदेश",
  },

  // OTHER PROVINCES
  {
    id: "law-prov-bagmati-01",
    title_ne: "बागमती प्रदेश अपाङ्गता भएका व्यक्तिको अधिकार सम्बन्धी ऐन, २०७९",
    title_en: "Bagmati Province Rights of Persons with Disabilities Act, 2079 BS",
    category: "act",
    category_name_ne: "ऐन",
    gov_level: "provincial",
    province_id: "bagmati",
    province_name_ne: "बागमती प्रदेश",
    issuing_authority: "बागमती प्रदेश सभा, हेटौंडा",
    publication_date_bs: "२०७९/०३/१०",
    effective_date_bs: "२०७९/०३/१०",
    is_amended: false,
    description_ne: "बागमती प्रदेशमा अपाङ्गता भएका व्यक्तिको सशक्तीकरण, जीविकोपार्जन तालिम र समावेशी विकास सम्बन्धी प्रादेशिक ऐन।",
    keywords: ["बागमती प्रदेश", "ऐन", "२०७९"],
    pdf_url: "#",
    file_size: "१.७ MB",
    source: "बागमती प्रदेश राजपत्र",
  },
  {
    id: "law-prov-gandaki-01",
    title_ne: "गण्डकी प्रदेश अपाङ्गता भएका व्यक्तिहरुको अधिकार संरक्षण ऐन, २०८१",
    title_en: "Gandaki Province Rights Protection of Persons with Disabilities Act, 2081 BS",
    category: "act",
    category_name_ne: "ऐन",
    gov_level: "provincial",
    province_id: "gandaki",
    province_name_ne: "गण्डकी प्रदेश",
    issuing_authority: "गण्डकी प्रदेश सभा, पोखरा",
    publication_date_bs: "२०८१/०१/२०",
    effective_date_bs: "२०८१/०१/२०",
    is_amended: false,
    description_ne: "गण्डकी प्रदेशका ११ जिल्लामा अपाङ्गतामैत्री सेवा प्रवाह र नीतिगत व्यवस्थाका लागि जारी भएको कानुन।",
    keywords: ["गण्डकी प्रदेश", "पोखरा", "ऐन", "२०८१"],
    pdf_url: "#",
    file_size: "१.५ MB",
    source: "गण्डकी प्रदेश सभा सचिवालय",
  },
  {
    id: "law-prov-lumbini-01",
    title_ne: "लुम्बिनी प्रदेश अपाङ्गता रोकथाम तथा पुनर्स्थापना नीति तथा कार्यविधि, २०८०",
    title_en: "Lumbini Province Disability Prevention and Rehabilitation Procedure, 2080 BS",
    category: "procedure",
    category_name_ne: "कार्यविधि",
    gov_level: "provincial",
    province_id: "lumbini",
    province_name_ne: "लुम्बिनी प्रदेश",
    issuing_authority: "सामाजिक विकास मन्त्रालय, लुम्बिनी प्रदेश",
    publication_date_bs: "२०८०/०६/१५",
    effective_date_bs: "२०८०/०६/१५",
    is_amended: false,
    description_ne: "लुम्बिनी प्रदेश भित्र अपाङ्गता पहिचान तथा रोकथाम, स्वावलम्बन केन्द्र र सहायक प्रविधि विकास कार्यविधि।",
    keywords: ["लुम्बिनी प्रदेश", "कार्यविधि", "पुनर्स्थापना"],
    pdf_url: "#",
    file_size: "१.३ MB",
    source: "लुम्बिनी प्रदेश राजपत्र",
  },
];
